services:
  api:
    build:
      context: ./api
      target: api
    env_file: .env
    ports:
      - 8000:80
    networks:
      - api_network


  workers:
    env_file: .env
    build:
      context: ./api
      target: workers
    networks:
      - api_network


  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: imagebot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - api_network


  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    env_file: .env
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes: 
      - redis:/data
    networks:
      - api_network

volumes:
  pgdata:
  redis:

networks:
  api_network:
    driver: bridge

